export const projects = [
    {
        slug: 'aegish',
        title: 'Aegish',
        description: 'A lightweight CLI application for quickly converting natural language into linux commands.',
        longDescription: '',
        image: '/images/project_images/aegish.png',
        github: 'https://github.com/zainmarshall/aegish',
        website: '',
        technologies: ['Python'],
    },
    {
        slug: 'bliss',
        title: 'Bliss',
        description: 'A truly effective MacOS blocker.',
        longDescription: '',
        github: 'https://github.com/zainmarshall/bliss',
        website: '',
        technologies: ['C++', 'Swift'],
    },
    {
        slug: 'zen-plus-plus',
        title: 'Zen++',
        description: 'A custom interpreted language designed for competitive programming.',
        longDescription: '',
        github: 'https://github.com/zainmarshall/zen-plus-plus',
        website: '',
        technologies: ['C++'],
    },
    {
        slug: 'scioly-id-bots',
        title: 'Science Olympiad ID Bots',
        description: 'Discord bots for practicing Science Olympiad identification events.',
        longDescription: '',
        github: 'https://github.com/zainmarshall/waterboiiii',
        links: [
            { label: 'Water Quality Bot', url: 'https://github.com/zainmarshall/waterboiiii' },
            { label: 'Botany Bot', url: 'https://github.com/zainmarshall/botanybot' },
        ],
        website: '',
        technologies: ['Python'],
    },
    {
        slug: 'portfolio',
        title: 'Portfolio Website',
        description: 'This website. Built with SvelteKit and Tailwind CSS.',
        longDescription: '',
        image: '/images/project_images/portfolio.png',
        github: 'https://github.com/zainmarshall/portfolio',
        website: 'https://zainm.me/',
        technologies: ['Svelte', 'Tailwind CSS', 'TypeScript'],
    },
];
